# Generated by Django 4.2.5 on 2023-10-21 22:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['purchased_date']},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment_status',
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('CANCELEED', 'Cancelled'), ('PENDING', 'Pending'), ('NO_STATUS', 'No_status')], default='NO_STATUS', max_length=50)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular transaction', primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.ticket')),
            ],
            options={
                'ordering': ['payment_status', 'payment_method', 'amount'],
            },
        ),
    ]
