# Generated by Django 4.2.5 on 2023-10-21 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_alter_ticket_options_remove_ticket_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentDetails',
            new_name='PaymentDetail',
        ),
    ]
